# Generated by Django 4.1.7 on 2023-03-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_link', models.TextField(null=True)),
                ('image_link', models.TextField(null=True)),
                ('rating', models.FloatField(null=True)),
                ('metascore', models.FloatField(null=True)),
                ('description', models.TextField(null=True)),
                ('votes', models.FloatField(null=True)),
                ('movie_name', models.TextField(null=True)),
                ('start_year', models.IntegerField(null=True)),
                ('end_year', models.IntegerField(null=True)),
                ('gross', models.FloatField(null=True)),
                ('certificate', models.TextField(null=True)),
                ('time', models.IntegerField(null=True)),
                ('genre', models.TextField(null=True)),
                ('director', models.TextField(null=True)),
                ('stars', models.TextField(null=True)),
                ('status', models.TextField(null=True)),
                ('certificate_meaning', models.TextField(null=True)),
                ('comedy', models.IntegerField(null=True)),
                ('Sci_fi', models.IntegerField(null=True)),
                ('horror', models.IntegerField(null=True)),
                ('romance', models.IntegerField(null=True)),
                ('action', models.IntegerField(null=True)),
                ('thriller', models.IntegerField(null=True)),
                ('drama', models.IntegerField(null=True)),
                ('mystery', models.IntegerField(null=True)),
                ('crime', models.IntegerField(null=True)),
                ('animation', models.IntegerField(null=True)),
                ('adventure', models.IntegerField(null=True)),
                ('fantasy', models.IntegerField(null=True)),
                ('family', models.IntegerField(null=True)),
                ('biography', models.IntegerField(null=True)),
                ('docum', models.IntegerField(null=True)),
                ('film_noir', models.IntegerField(null=True)),
                ('history', models.IntegerField(null=True)),
                ('music', models.IntegerField(null=True)),
                ('musical', models.IntegerField(null=True)),
                ('short', models.IntegerField(null=True)),
                ('sport', models.IntegerField(null=True)),
                ('superhero', models.IntegerField(null=True)),
                ('war', models.IntegerField(null=True)),
                ('western', models.IntegerField(null=True)),
                ('all', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('genre', models.TextField(null=True)),
                ('movie', models.TextField(null=True)),
            ],
        ),
    ]
