# Generated by Django 4.1.7 on 2023-03-16 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='Sci_fi',
            new_name='sci_fi',
        ),
    ]
