# Generated by Django 4.1.7 on 2023-03-16 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_rename_sci_fi_details_sci_fi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='all',
            new_name='tag',
        ),
    ]
